name: Hourly inventory sync

on:
  schedule:
    - cron: '0 * * * *'      
  workflow_dispatch:         

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run updater
        env:
          SHOP_TOKEN: ${{ secrets.SHOP_TOKEN }}
          LOCATION_ID: ${{ secrets.LOCATION_ID }}
          SHOPIFY_SHOP: ${{ secrets.SHOPIFY_SHOP }}
        run: bash run_inventory.sh
  tracking:                
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - name: Run tracking updater
        env:
          SHOP_TOKEN:   ${{ secrets.SHOP_TOKEN }}
          LOCATION_ID:  ${{ secrets.LOCATION_ID }}
          SHOPIFY_SHOP: ${{ secrets.SHOPIFY_SHOP }}
        run: python update_tracking.py
