name: Hourly inventory sync

on:
  schedule:
    - cron: '0 * * * *'      # every hour
  workflow_dispatch:         # lets you run it manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run updater
        env:
          SHOP_TOKEN: ${{ secrets.SHOP_TOKEN }}
          LOCATION_ID: ${{ secrets.LOCATION_ID }}
          SHOPIFY_SHOP: ${{ secrets.SHOPIFY_SHOP }}
        run: |
          bash run_inventory.sh
